// GET PRODUCT
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

// GET PRODUCT DETAIL
export const GET_PRODUCT_DETAIL_REQUEST = "GET_PRODUCT_DETAIL_REQUEST";
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS";
export const GET_PRODUCT_DETAIL_FAIL = "GET_PRODUCT_DETAIL_FAIL";
export const GET_PRODUCT_DETAIL_RESET = "GET_PRODUCT_DETAIL_RESET";

// Counter
export const GET_COUNTER_REQUEST = "GET_COUNTER_REQUEST";
export const GET_COUNTER_INCREASE = "GET_COUNTER_INCREASE";
export const GET_COUNTER_DECREASE = "GET_COUNTER_DECREASE";
export const GET_COUNTER_FAIL = "GET_COUNTER_FAIL";
